import { Campanha } from '../types'
import { novoId, agoraISO } from '../utils/id'

// Campanha de exemplo local. Todos os dados abaixo podem ser editados
// ou apagados livremente pela interface — servem apenas como ponto de partida.
export function criarCampanhaExemplo(): Campanha {
  const agora = agoraISO()

  return {
    id: novoId('campanha'),
    nomeCampanha: 'Oficina de Campo — O Protocolo Mercer',
    temporadaAtual: 1,
    episodioAtual: 1,
    protagonista: {
      nome: 'Caleb Mercer',
      condicaoFisica: 'Exausto, leves queimaduras nas mãos, subnutrido',
      localizacaoAtual: 'Galpão improvisado, terreno baldio nos arredores de Coyote Flat, Nevada',
      objetivoImediato: 'Estabilizar o núcleo antes que a fissura se abra por completo',
      nivelRisco: 'alto',
    },
    estabilidadePortal: 89,
    integridadeNucleo: 41,
    ultimaAlteracao: agora,
    itens: [
      {
        id: novoId('item'),
        nome: 'Anel de Portal — Protótipo Mk1',
        categoria: 'experimental',
        descricao:
          'Estrutura de metal reciclado soldada à mão, com núcleo de cristal instável no centro.',
        quantidade: 1,
        pesoOuEspaco: 0,
        localizacao: 'laboratorio',
        estado: 'instavel',
        cargaAtual: 89,
        cargaMaxima: 100,
        origem: 'Construído por Caleb ao longo de onze meses',
        funcaoConhecida: 'Abrir uma passagem estável entre pontos de realidades diferentes',
        limitacoesConhecidas: 'Consome energia de forma imprevisível; não deve ultrapassar 90% de carga',
        riscosConhecidos: 'Fissura no núcleo pode se expandir sob sobrecarga',
        informacoesDesconhecidas: 'Origem exata da instabilidade ainda não identificada',
        tags: ['portal', 'experimental', 'núcleo'],
        observacoes: '',
        sessaoObtido: 1,
        dataObtido: agora,
        arquivado: false,
        historico: [
          { id: novoId('hist'), data: agora, descricao: 'Item criado na campanha de exemplo' },
        ],
      },
      {
        id: novoId('item'),
        nome: 'Luvas Técnicas Queimadas',
        categoria: 'equipamento',
        descricao: 'Par de luvas resistentes ao calor, já com marcas de uso extremo.',
        quantidade: 1,
        pesoOuEspaco: 1,
        localizacao: 'carregado',
        estado: 'danificado',
        origem: 'Compradas em um ferro-velho industrial há dois anos',
        funcaoConhecida: 'Proteção contra calor e choques elétricos leves',
        limitacoesConhecidas: 'Isolamento comprometido na palma direita',
        riscosConhecidos: 'Pode falhar em contato prolongado com o núcleo exposto',
        informacoesDesconhecidas: '',
        tags: ['proteção'],
        observacoes: '',
        sessaoObtido: 1,
        dataObtido: agora,
        arquivado: false,
        historico: [
          { id: novoId('hist'), data: agora, descricao: 'Item criado na campanha de exemplo' },
        ],
      },
      {
        id: novoId('item'),
        nome: 'Componentes de Cristal Bruto',
        categoria: 'consumivel',
        descricao: 'Fragmentos usados para estabilizar ou substituir o núcleo do portal.',
        quantidade: 3,
        pesoOuEspaco: 1,
        localizacao: 'laboratorio',
        estado: 'intacto',
        origem: 'Extraídos de sucata industrial local',
        funcaoConhecida: 'Reparo de emergência do núcleo de cristal',
        limitacoesConhecidas: 'Cada fragmento suporta apenas um reparo',
        riscosConhecidos: 'Instabilidade se usados sob carga acima de 80%',
        informacoesDesconhecidas: 'Reação exata dos fragmentos com o núcleo trincado é desconhecida',
        tags: ['reparo', 'cristal'],
        observacoes: '',
        sessaoObtido: 1,
        dataObtido: agora,
        arquivado: false,
        historico: [
          { id: novoId('hist'), data: agora, descricao: 'Item criado na campanha de exemplo' },
        ],
      },
    ],
    recursos: [
      {
        id: novoId('rec'),
        nome: 'Energia do Laboratório',
        valorAtual: 62,
        valorMaximo: 100,
        unidade: '%',
        descricao: 'Energia disponível na rede improvisada do galpão',
        corAlerta: 'ciano',
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Recurso criado' }],
      },
      {
        id: novoId('rec'),
        nome: 'Dinheiro Disponível',
        valorAtual: 340,
        unidade: 'USD',
        descricao: 'Dinheiro em espécie guardado no galpão',
        corAlerta: 'ambar',
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Recurso criado' }],
      },
      {
        id: novoId('rec'),
        nome: 'Integridade do Núcleo de Cristal',
        valorAtual: 41,
        valorMaximo: 100,
        unidade: '%',
        descricao: 'Estado estrutural do núcleo do portal, atualmente trincado',
        corAlerta: 'ferrugem',
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Recurso criado' }],
      },
      {
        id: novoId('rec'),
        nome: 'Tempo Estimado até Falha Crítica',
        valorAtual: 4,
        unidade: 'minutos',
        descricao: 'Estimativa de Caleb sob pressão — pode estar errada',
        corAlerta: 'ferrugem',
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Recurso criado' }],
      },
    ],
    falhas: [
      {
        id: novoId('falha'),
        equipamentoId: null,
        equipamentoNome: 'Anel de Portal — Protótipo Mk1',
        nomeFalha: 'Fissura no núcleo de cristal',
        gravidade: 'grave',
        descricao: 'Uma rachadura visível atravessa o núcleo, liberando um filete de luz roxa.',
        sintomas: 'Vazamento de luz escura, leituras de energia oscilando entre positivo e negativo',
        causa: 'imprevisivel',
        causaDetalhe: 'Sobrecarga durante a primeira ativação estável',
        dataDescoberta: agora,
        recursoExigidoReparo: 'Componentes de Cristal Bruto',
        tempoEstimadoReparo: 'Desconhecido — nunca reparado antes',
        riscoPiora: 'Alto se a carga ultrapassar 90%',
        status: 'ativa',
        consequenciaAssociada: 'Abertura instável pode não fechar completamente',
        geradaAleatoriamente: false,
        sessaoOrigem: 1,
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Falha registrada' }],
      },
    ],
    personagens: [
      {
        id: novoId('npc'),
        nome: 'Silhueta Não Identificada',
        funcaoNarrativa: 'Desconhecida — observada do outro lado do portal',
        localizacaoAtual: 'Do outro lado do anel',
        realidadeOrigem: 'Desconhecida',
        relacaoComProtagonista: 'Nenhum contato direto ainda',
        objetivoConhecido: '',
        confianca: 0,
        dividaOuPromessa: '',
        segredo: 'A ser definido pelo narrador conforme a história avança',
        segredoNivel: 'segredo_narrador',
        segredoRevelado: false,
        estadoAtual: 'Parada, observando Caleb',
        ultimaInteracao: agora,
        sessaoIntroduzido: 1,
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Personagem introduzido' }],
      },
    ],
    registrosNarrativos: [
      {
        id: novoId('narr'),
        tipo: 'pista',
        titulo: 'Chamada com padrão desconhecido',
        descricao:
          'O telefone de Caleb tocou com um padrão de três notas que ele nunca programou, sincronizado ao zumbido do portal.',
        status: 'ativa',
        personagensEnvolvidos: [],
        episodioOrigem: 1,
        ultimaAtualizacao: agora,
        proximaConsequenciaPossivel: 'Pode indicar contato externo monitorando o experimento',
        conexoes: [],
        visivelProtagonista: true,
        historico: [{ id: novoId('hist'), data: agora, descricao: 'Pista registrada' }],
      },
    ],
    sessoes: [],
    auditoria: [
      {
        id: novoId('aud'),
        dataHora: agora,
        tipo: 'sistema',
        objetoAlterado: 'Campanha',
        valorAnterior: '—',
        valorNovo: 'Campanha de exemplo criada',
        motivo: 'Inicialização do sistema',
        sessaoAssociada: null,
      },
    ],
    snapshots: [],
  }
}
